version: 0.2

phases:
  install:
    runtime-versions:
       java: openjdk8
  build:
    commands:
       - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
       - aws s3 cp s3://nexuscredentials-cmmaven/settings.xml .
       - gradle build
       - gradle publishToMavenLocal -s settings.xml  
