:status:
:outfilesuffix: .adoc
:uri-build-status: https://github.com/Sphereon-Opensource/factom-identity-client-java/actions/workflows/gradle.yml
:img-build-status: https://github.com/Sphereon-Opensource/factom-identity-client-java/actions/workflows/gradle.yml/badge.svg


++++
<h1 align="center">
<br>
<a href="https://www.sphereon.com"><img src="https://sphereon.com/content/themes/sphereon/assets/img/logo.svg" alt="Sphereon" width="400"></a>
<br>Factom Identity Java Client
<br>
</h1>
++++


ifdef::status[]
image:{img-build-status}[Build Status Badge,link={uri-build-status}]
endif::[]

== Active Development
_IMPORTANT: This software still is in early development stage. As such you should expect breaking changes in APIs, we expect to keep that to a minimum though._


== Factom Identity Java Client

A Factom Java client to interact with Factom identities and Decentralized Identifiers.


== Maven installation
This is a gradle project but maven snapshots and releases are distributed on the Nexus installation of Sphereon at
https://nexus.qa.sphereon.com/repository/sphereon-opensource-releases/

You need at least the following dependencies in your application

....

<dependency>
    <groupId>org.blockchain-innovation.factom.client</groupId>
    <artifactId>factom-client-impl</artifactId>
    <version>0.4.1</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>org.blockchain-innovation.factom.client</groupId>
    <artifactId>logger-slf4j</artifactId>
    <version>0.4.1</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>org.blockchain-innovation.factom.client</groupId>
    <artifactId>json-converter-gson</artifactId>
    <version>0.4.1</version>
    <scope>compile</scope>
</dependency>

<!-- At least one of the following did model dependencies -->
<!-- TODO: extend with non-gson dependency options -->
<dependency>
    <groupId>org.factomprotocol.identity</groupId>
    <artifactId>factom-did-models-java-gson</artifactId>
    <version>0.3.1</version>
</dependency>

<!-- Offline signing support -->
<dependency>
    <groupId>org.blockchain-innovation.factom.client</groupId>
    <artifactId>factom-client-offline-signing</artifactId>
    <version>0.4.1</version>
    <scope>compile</scope>
</dependency>

....

== Active Development
IMPORTANT: This software still is in early development stage. As such you should expect breaking changes in APIs, we expect
to keep that to a minimum though.
